INSERT INTO PARKING (ID, LICENSE, STATE, MODEL, COLOR, ENTRY_DATE, EXIT_DATE, BILL)
VALUES (50, 'AAA1111', 'SP', 'CELTA', 'BRANCO', CURRENT_TIMESTAMP, NULL, 10.00);

INSERT INTO PARKING (ID, LICENSE, STATE, MODEL, COLOR, ENTRY_DATE, EXIT_DATE, BILL)
VALUES (51, 'BBB1111', 'MG', 'FOX', 'CINZA', CURRENT_TIMESTAMP, NULL, 15.00);

INSERT INTO PARKING (ID, LICENSE, STATE, MODEL, COLOR, ENTRY_DATE, EXIT_DATE, BILL)
VALUES (52, 'AAA2222', 'PR', 'MONZA', 'PRETO', CURRENT_TIMESTAMP, NULL, 20.00);

INSERT INTO PARKING (ID, LICENSE, STATE, MODEL, COLOR, ENTRY_DATE, EXIT_DATE, BILL)
VALUES (53, 'BBB2222', 'AM', 'VOYAGE', 'AZUL', CURRENT_TIMESTAMP, NULL, 100.00);
